# Generated by Django 3.2 on 2022-02-25 20:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CentroCusto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='UUID Código único não sequencial', unique=True, verbose_name='UUID')),
                ('ativo', models.BooleanField(default=True, help_text='Se o registro está ativo ou não', verbose_name='Ativo')),
                ('data_cadastro', models.DateField(auto_now_add=True, help_text='Data da criação do registro', verbose_name='Data do cadastro')),
                ('hora_cadastro', models.TimeField(auto_now_add=True, help_text='Hora da criação do registro', verbose_name='Hora do cadastro')),
                ('codigo', models.CharField(help_text='Código do centro de custo ex: 1.101.1000', max_length=15, verbose_name='Código')),
                ('descricao', models.CharField(help_text='Descrição do centro de custo ex: Departamento Pessoal', max_length=255, verbose_name='Descrição')),
                ('tipo', models.CharField(choices=[('A', 'Analítico'), ('S', 'Sintético')], help_text='Tipo do centro de custo do lançamento ex: A = Analítico ou S = Sintético', max_length=1, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Centro de Custo',
                'verbose_name_plural': 'Centro de Custos',
                'db_table': 'centro_custo',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ContaContabil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='UUID Código único não sequencial', unique=True, verbose_name='UUID')),
                ('ativo', models.BooleanField(default=True, help_text='Se o registro está ativo ou não', verbose_name='Ativo')),
                ('data_cadastro', models.DateField(auto_now_add=True, help_text='Data da criação do registro', verbose_name='Data do cadastro')),
                ('hora_cadastro', models.TimeField(auto_now_add=True, help_text='Hora da criação do registro', verbose_name='Hora do cadastro')),
                ('codigo', models.CharField(help_text='Código da conta contábil ex: 2.202.2000', max_length=15, verbose_name='Código')),
                ('descricao', models.CharField(help_text='Descrição da conta contábil ex: Compra de materiais de escritório', max_length=255, verbose_name='Descrição')),
                ('tipo', models.CharField(choices=[('A', 'Analítico'), ('S', 'Sintético')], help_text='Tipo da conta contábil do lançamento ex: A = Analítico ou S = Sintético', max_length=1, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Conta Contábil',
                'verbose_name_plural': 'Contas Contábeis',
                'db_table': 'conta_contabil',
                'ordering': ['-id'],
            },
        ),
    ]
