# Generated by Django 3.2 on 2022-02-25 20:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agrupamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='lancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='UUID Código único não sequencial', unique=True, verbose_name='UUID')),
                ('ativo', models.BooleanField(default=True, help_text='Se o registro está ativo ou não', verbose_name='Ativo')),
                ('data_cadastro', models.DateField(auto_now_add=True, help_text='Data da criação do registro', verbose_name='Data do cadastro')),
                ('hora_cadastro', models.TimeField(auto_now_add=True, help_text='Hora da criação do registro', verbose_name='Hora do cadastro')),
                ('descricao', models.CharField(help_text='Descrição do centro de custo ex: Departamento Pessoal', max_length=255, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor do lançamento', max_digits=11, verbose_name='Valor')),
                ('data_data', models.DateField(help_text='Data do lançamento da', verbose_name='Data do Lançamento')),
                ('tipo', models.CharField(choices=[('D', 'Débito'), ('C', 'Crédito')], help_text='Tipo do lancamento ex: D = Débito ou C = Crédito', max_length=1, verbose_name='Tipo')),
                ('baixado', models.BooleanField(default=False, help_text='Se o lançamento foi recebido/pago', verbose_name='Baixado')),
                ('centro_custo', models.ForeignKey(blank=True, help_text='Centro de custo do lançamento', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agrupamento_centro_custo_lancamento', to='agrupamento.centrocusto', verbose_name='Centro de Custo')),
                ('conta_contabil', models.ForeignKey(blank=True, help_text='Conta contábil do lançamento', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agrupamento_conta_contabil_lancamento', to='agrupamento.contacontabil', verbose_name='Conta Contábil')),
            ],
            options={
                'verbose_name': 'Lançamento',
                'verbose_name_plural': 'Lançamentos',
                'db_table': 'lancamento',
                'ordering': ['-id'],
            },
        ),
    ]
