# Generated by Django 3.2 on 2022-03-02 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lancamento', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lancamento',
            old_name='data_data',
            new_name='data',
        ),
    ]
